In [8]:
import pandas as pd
import numpy as np

In [31]:
data = pd.read_csv("NYC_Jobs.csv")
data = data[['Job ID','Civil Service Title','Agency','Posting Type','Job Category','Salary Range From','Salary Range To']]
data.head()

,Job ID,Civil Service Title,Agency,Posting Type,Job Category,Salary Range From,Salary Range To
0,424339,Public health nurse,DEPT OF HEALTH/MENTAL HYGIENE,External,Health,84252.0,84252.0
1,379094,Cert it developer (app),NYC EMPLOYEES RETIREMENT SYS,External,"Technology, Data & Innovation",82884.0,116391.0
2,520417,Executive agency counsel,NYC HOUSING AUTHORITY,External,Legal Affairs,105000.0,125000.0
3,233549,Certified it administrator (la,NYC EMPLOYEES RETIREMENT SYS,External,Information Technology & Telecommunications,87203.0,131623.0
4,510256,Associate human rights special,HUMAN RIGHTS COMMISSION,External,Constituent Services & Community Programs,58449.0,67216.0

In [6]:
# apply can be used with dataframe and series

In [13]:
# you can apply a pre-defined function to it
data['Salary Range From'].apply(np.sqrt)

0       290.261951
1       287.895814
2       324.037035
3       295.301541
4       241.762280
           ...
3768    292.183162
3769    273.221522
3770    316.227766
3771    205.640463
3772    249.793915
Name: Salary Range From, Length: 3773, dtype: float64

In [34]:
# depending on whether you apply it to the columns or rows you will get a different result
data[['Salary Range From','Salary Range To']].apply(np.mean, axis=0)

Salary Range From    57657.939466
Salary Range To      79660.249595
dtype: float64

In [37]:
data[['Salary Range From','Salary Range To']].apply(np.mean, axis=1)

0        84252.0
1        99637.5
2       115000.0
3       109413.0
4        62832.5
          ...
3768    102627.0
3769     80248.5
3770    107500.0
3771     50844.0
3772     67077.0
Length: 3773, dtype: float64

In [35]:
# it returns a new series or dataframe object 
# so if you don't assign it to anything, nothing will change in your original dataset
data['Avg salary'] = data[['Salary Range From','Salary Range To']].apply(np.mean, axis=1)

In [36]:
data

,Job ID,Civil Service Title,Agency,Posting Type,Job Category,Salary Range From,Salary Range To,Avg salary
0,424339,Public health nurse,DEPT OF HEALTH/MENTAL HYGIENE,External,Health,84252.0,84252.0,84252.0
1,379094,Cert it developer (app),NYC EMPLOYEES RETIREMENT SYS,External,"Technology, Data & Innovation",82884.0,116391.0,99637.5
2,520417,Executive agency counsel,NYC HOUSING AUTHORITY,External,Legal Affairs,105000.0,125000.0,115000.0
3,233549,Certified it administrator (la,NYC EMPLOYEES RETIREMENT SYS,External,Information Technology & Telecommunications,87203.0,131623.0,109413.0
4,510256,Associate human rights special,HUMAN RIGHTS COMMISSION,External,Constituent Services & Community Programs,58449.0,67216.0,62832.5
...,...,...,...,...,...,...,...,...
3768,457839,Certified it administrator (la,NYC EMPLOYEES RETIREMENT SYS,Internal,"Technology, Data & Innovation",85371.0,119883.0,102627.0
3769,527141,Associate housing development,HOUSING PRESERVATION & DVLPMNT,Internal,"Engineering, Architecture, & Planning",74650.0,85847.0,80248.5
3770,509443,Senior it architect,FINANCIAL INFO SVCS AGENCY,Internal,"Technology, Data & Innovation",100000.0,115000.0,107500.0
3771,352367,Economist,DEPT OF HEALTH/MENTAL HYGIENE,Internal,"Finance, Accounting, & Procurement",42288.0,59400.0,50844.0
3772,478739,Agency attorney interne,HUMAN RIGHTS COMMISSION,External,Legal Affairs,62397.0,71757.0,67077.0

In [25]:
# you can create a custom function and apply it to the dataframe
def capitalize_position(title):
    title_lower = title.lower()
    title_final = title_lower.capitalize()
    return title_final

data['Civil Service Title'].apply(make_lower_case)

0                  Public health nurse
1              Cert it developer (app)
2             Executive agency counsel
3       Certified it administrator (la
4       Associate human rights special
                     ...
3768    Certified it administrator (la
3769     Associate housing development
3770               Senior it architect
3771                         Economist
3772           Agency attorney interne
Name: Civil Service Title, Length: 3773, dtype: object

In [26]:
# again you would need to assign it to the dataframe
data['Civil Service Title'] = data['Civil Service Title'].apply(make_lower_case)

In [53]:
# you can write lambda functions
data.apply(lambda x: x.tolist(), axis=1)

0       [424339, Public health nurse, DEPT OF HEALTH/M...
1       [379094, Cert it developer (app), NYC EMPLOYEE...
2       [520417, Executive agency counsel, NYC HOUSING...
3       [233549, Certified it administrator (la, NYC E...
4       [510256, Associate human rights special, HUMAN...
                              ...
3768    [457839, Certified it administrator (la, NYC E...
3769    [527141, Associate housing development, HOUSIN...
3770    [509443, Senior it architect, FINANCIAL INFO S...
3771    [352367, Economist, DEPT OF HEALTH/MENTAL HYGI...
3772    [478739, Agency attorney interne, HUMAN RIGHTS...
Length: 3773, dtype: object

In [55]:
# if the result of this apply process is a list, you can decide to do different things with that list
# expand will assign each element of the list to a different column
data.apply(lambda x: x.tolist(), axis=1, result_type='expand')

,0,1,2,3,4,5,6,7
0,424339,Public health nurse,DEPT OF HEALTH/MENTAL HYGIENE,External,Health,84252.0,84252.0,84252.0
1,379094,Cert it developer (app),NYC EMPLOYEES RETIREMENT SYS,External,"Technology, Data & Innovation",82884.0,116391.0,99637.5
2,520417,Executive agency counsel,NYC HOUSING AUTHORITY,External,Legal Affairs,105000.0,125000.0,115000.0
3,233549,Certified it administrator (la,NYC EMPLOYEES RETIREMENT SYS,External,Information Technology & Telecommunications,87203.0,131623.0,109413.0
4,510256,Associate human rights special,HUMAN RIGHTS COMMISSION,External,Constituent Services & Community Programs,58449.0,67216.0,62832.5
...,...,...,...,...,...,...,...,...
3768,457839,Certified it administrator (la,NYC EMPLOYEES RETIREMENT SYS,Internal,"Technology, Data & Innovation",85371.0,119883.0,102627.0
3769,527141,Associate housing development,HOUSING PRESERVATION & DVLPMNT,Internal,"Engineering, Architecture, & Planning",74650.0,85847.0,80248.5
3770,509443,Senior it architect,FINANCIAL INFO SVCS AGENCY,Internal,"Technology, Data & Innovation",100000.0,115000.0,107500.0
3771,352367,Economist,DEPT OF HEALTH/MENTAL HYGIENE,Internal,"Finance, Accounting, & Procurement",42288.0,59400.0,50844.0
3772,478739,Agency attorney interne,HUMAN RIGHTS COMMISSION,External,Legal Affairs,62397.0,71757.0,67077.0

In [61]:
# broadcast would do that and keep the column names
# see that in expand the column names are newly created to go from 0 to 7
data.apply(lambda x: x.tolist(), axis=1, result_type='broadcast')

,Job ID,Civil Service Title,Agency,Posting Type,Job Category,Salary Range From,Salary Range To,Avg salary
0,424339,Public health nurse,DEPT OF HEALTH/MENTAL HYGIENE,External,Health,84252,84252,84252
1,379094,Cert it developer (app),NYC EMPLOYEES RETIREMENT SYS,External,"Technology, Data & Innovation",82884,116391,99637.5
2,520417,Executive agency counsel,NYC HOUSING AUTHORITY,External,Legal Affairs,105000,125000,115000
3,233549,Certified it administrator (la,NYC EMPLOYEES RETIREMENT SYS,External,Information Technology & Telecommunications,87203,131623,109413
4,510256,Associate human rights special,HUMAN RIGHTS COMMISSION,External,Constituent Services & Community Programs,58449,67216,62832.5
...,...,...,...,...,...,...,...,...
3768,457839,Certified it administrator (la,NYC EMPLOYEES RETIREMENT SYS,Internal,"Technology, Data & Innovation",85371,119883,102627
3769,527141,Associate housing development,HOUSING PRESERVATION & DVLPMNT,Internal,"Engineering, Architecture, & Planning",74650,85847,80248.5
3770,509443,Senior it architect,FINANCIAL INFO SVCS AGENCY,Internal,"Technology, Data & Innovation",100000,115000,107500
3771,352367,Economist,DEPT OF HEALTH/MENTAL HYGIENE,Internal,"Finance, Accounting, & Procurement",42288,59400,50844
3772,478739,Agency attorney interne,HUMAN RIGHTS COMMISSION,External,Legal Affairs,62397,71757,67077